from __future__ import annotations

from modules.connectors.apps._definition_common import (
    BASE_CONNECTION_CONFIG,
    BASE_TOKEN_AUTH,
    GOOGLE_AUTH,
    GOOGLE_CONNECTION_CONFIG,
    AuthSpec,
    ConnectorDefinition,
    FieldDescriptor,
    OperationSpec,
    StreamDefinition,
    WriteConfig,
)


CONNECTOR_DEFINITION = ConnectorDefinition(
        connector_key='base_workflow',
        display_name='Base Workflow',
        summary='Workflows, stages, jobs, posts and comments from Base Workflow.',
        auth_spec=BASE_TOKEN_AUTH,
        api_prefix='/extapi/v1',
        base_url_template='https://workflow.{domain}/extapi/v1',
        supported_modules=('backup', 'pipeline', 'automation'),
        icon='folder-kanban',
        color='#7c3aed',
        bg_color='#f5f3ff',
        connection_config=BASE_CONNECTION_CONFIG,
        streams=(
            StreamDefinition(
                stream_key='workflows',
                display_name='Workflows',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                read_operation='get_all_workflows',
                supported_modules=('backup', 'pipeline'),
            ),
            StreamDefinition(
                stream_key='stages',
                display_name='Stages',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='workflows',
                read_operation='get_workflow_stages',
                config_fields=(
                    FieldDescriptor(name='workflow_id', field_type='string', required=True, description='Workflow ID'),
                ),
                supported_modules=('backup',),
            ),
            StreamDefinition(
                stream_key='jobs',
                display_name='Jobs',
                capabilities=('read', 'write'),
                sync_modes=('full_refresh', 'incremental'),
                primary_key='id',
                parent_stream='workflows',
                read_operation='get_workflow_jobs',
                write_operation='create_job',
                config_fields=(
                    FieldDescriptor(name='workflow_id', field_type='string', required=True, description='Workflow ID'),
                ),
                write_config=WriteConfig(
                    supported_modes=('append',),
                    default_mode='append',
                    target_kind='resource',
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
            StreamDefinition(
                stream_key='job_details',
                display_name='Job Details',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='jobs',
                read_operation='get_job',
                config_fields=(
                    FieldDescriptor(name='job_id', field_type='string', required=True, description='Job ID'),
                ),
                supported_modules=('backup',),
            ),
            StreamDefinition(
                stream_key='job_custom_tables',
                display_name='Job Custom Tables',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                parent_stream='jobs',
                read_operation='get_job_custom_table',
                config_fields=(
                    FieldDescriptor(name='job_id', field_type='string', required=True, description='Job ID'),
                ),
                supported_modules=('backup',),
            ),
            StreamDefinition(
                stream_key='posts',
                display_name='Posts',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                parent_stream='jobs',
                read_operation='get_job_posts',
                config_fields=(
                    FieldDescriptor(name='job_id', field_type='string', required=True, description='Job ID'),
                ),
                supported_modules=('backup',),
            ),
            StreamDefinition(
                stream_key='comments',
                display_name='Comments',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                parent_stream='posts',
                read_operation='get_job_comments',
                config_fields=(
                    FieldDescriptor(name='post_id', field_type='string', required=True, description='Post ID'),
                ),
                supported_modules=('backup',),
            ),
        ),
        operations=(
            OperationSpec(operation_key='get_all_workflows', summary='List all workflows', api_endpoint='/workflows/get', pagination='page'),
            OperationSpec(operation_key='get_workflow', summary='Get a workflow', api_endpoint='/workflow/get', required_fields=('id',)),
            OperationSpec(operation_key='get_workflow_stages', summary='List stages in a workflow', api_endpoint='/workflow/stages', required_fields=('id',)),
            OperationSpec(operation_key='get_workflow_jobs', summary='List jobs in a workflow', api_endpoint='/workflow/jobs', required_fields=('id',), pagination='cursor'),
            OperationSpec(operation_key='get_all_jobs', summary='List all jobs with filters', api_endpoint='/jobs/get', pagination='cursor'),
            OperationSpec(operation_key='get_job', summary='Get a job', api_endpoint='/job/get', required_fields=('id',)),
            OperationSpec(operation_key='get_job_custom_table', summary='Get job custom table', api_endpoint='/job/custom.table', required_fields=('id',)),
            OperationSpec(operation_key='get_job_posts', summary='Get posts of a job', api_endpoint='/job/post/load', required_fields=('id',)),
            OperationSpec(operation_key='get_job_comments', summary='Get comments of a post', api_endpoint='/job/comment/load', required_fields=('hid',)),
            OperationSpec(operation_key='create_job', summary='Create a job', api_endpoint='/job/create', required_fields=('creator_username', 'workflow_id', 'name'), capability='write'),
            OperationSpec(operation_key='edit_job', summary='Edit a job', api_endpoint='/job/edit', required_fields=('id',), capability='write'),
            OperationSpec(operation_key='move_next', summary='Move job to next stage', api_endpoint='/job/next', required_fields=('id', 'mover_username'), capability='write'),
            OperationSpec(operation_key='move_back', summary='Move job back', api_endpoint='/job/back', required_fields=('id', 'mover_username', 'stage_id'), capability='write'),
            OperationSpec(operation_key='mark_failed', summary='Mark job as failed', api_endpoint='/job/fail', required_fields=('id', 'username', 'failed_reason_id'), capability='write'),
        ),
    )
