from __future__ import annotations

from modules.connectors.apps._definition_common import (
    BASE_CONNECTION_CONFIG,
    BASE_TOKEN_AUTH,
    GOOGLE_AUTH,
    GOOGLE_CONNECTION_CONFIG,
    AuthSpec,
    ConnectorDefinition,
    FieldDescriptor,
    OperationSpec,
    StreamDefinition,
    WriteConfig,
)


CONNECTOR_DEFINITION = ConnectorDefinition(
        connector_key='base_hrm',
        display_name='Base HRM',
        summary='Employees, departments, positions, merits, payroll and checkin data from Base HRM.',
        auth_spec=BASE_TOKEN_AUTH,
        api_prefix='/extapi/v1',
        base_url_template='https://hrm.{domain}/extapi/v1',
        supported_modules=('pipeline',),
        icon='users',
        color='#0891b2',
        bg_color='#ecfeff',
        connection_config=BASE_CONNECTION_CONFIG,
        streams=(
            StreamDefinition(stream_key='employees', display_name='Employees', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='employee_details', display_name='Employee Details', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id', parent_stream='employees'),
            StreamDefinition(stream_key='departments', display_name='Departments', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='positions', display_name='Positions', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='levels', display_name='Levels', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='groups', display_name='Groups', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='teams', display_name='Teams', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='employee_types', display_name='Employee Types', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='merits', display_name='Merits', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='merit_details', display_name='Merit Details', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id', parent_stream='merits'),
            StreamDefinition(stream_key='merit_employees', display_name='Merit Employees', capabilities=('read',), sync_modes=('full_refresh',), parent_stream='merits'),
            StreamDefinition(stream_key='merit_categories', display_name='Merit Categories', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='merit_types', display_name='Merit Types', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='payroll_cycles', display_name='Payroll Cycles', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='payroll_detail', display_name='Payroll Detail', capabilities=('read',), sync_modes=('full_refresh',), parent_stream='payroll_cycles'),
            StreamDefinition(stream_key='payroll_summary', display_name='Payroll Summary', capabilities=('read',), sync_modes=('full_refresh',), parent_stream='payroll_cycles'),
            StreamDefinition(stream_key='payroll_categories', display_name='Payroll Categories', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='payroll_formulas', display_name='Payroll Formulas', capabilities=('read',), sync_modes=('full_refresh',)),
            StreamDefinition(stream_key='checkin_logs', display_name='Checkin Logs', capabilities=('read',), sync_modes=('full_refresh', 'incremental')),
            StreamDefinition(stream_key='checkin_offers', display_name='Checkin Offers', capabilities=('read',), sync_modes=('full_refresh',)),
            StreamDefinition(stream_key='checkin_schedules', display_name='Checkin Schedules', capabilities=('read',), sync_modes=('full_refresh',)),
            StreamDefinition(stream_key='checkin_shifts', display_name='Checkin Shifts', capabilities=('read',), sync_modes=('full_refresh',), primary_key='id'),
            StreamDefinition(stream_key='checkin_holiday_schedules', display_name='Holiday Schedules', capabilities=('read',), sync_modes=('full_refresh',)),
            StreamDefinition(stream_key='checkin_summary', display_name='Checkin Summary', capabilities=('read',), sync_modes=('full_refresh',)),
        ),
    )
