from __future__ import annotations

from modules.connectors.apps._definition_common import (
    BASE_CONNECTION_CONFIG,
    BASE_TOKEN_AUTH,
    GOOGLE_AUTH,
    GOOGLE_CONNECTION_CONFIG,
    AuthSpec,
    ConnectorDefinition,
    FieldDescriptor,
    OperationSpec,
    StreamDefinition,
    WriteConfig,
)


CONNECTOR_DEFINITION = ConnectorDefinition(
        connector_key='base_request',
        display_name='Base Request',
        summary='Groups, requests, posts and comments from Base Request.',
        auth_spec=BASE_TOKEN_AUTH,
        api_prefix='/extapi/v1',
        base_url_template='https://request.{domain}/extapi/v1',
        supported_modules=('backup', 'pipeline', 'automation'),
        icon='inbox',
        color='#ea580c',
        bg_color='#fff7ed',
        connection_config=BASE_CONNECTION_CONFIG,
        streams=(
            StreamDefinition(
                stream_key='groups',
                display_name='Groups',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                read_operation='get_all_groups',
                supported_modules=('backup', 'pipeline'),
            ),
            StreamDefinition(
                stream_key='requests',
                display_name='Requests',
                capabilities=('read', 'write'),
                sync_modes=('full_refresh', 'incremental'),
                primary_key='id',
                parent_stream='groups',
                read_operation='get_requests',
                write_operation='create_request',
                config_fields=(
                    FieldDescriptor(name='group_id', field_type='string', required=True, description='Request group ID'),
                ),
                write_config=WriteConfig(
                    supported_modes=('append',),
                    default_mode='append',
                    target_kind='resource',
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
            StreamDefinition(
                stream_key='request_details',
                display_name='Request Details',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='requests',
                read_operation='get_request',
                config_fields=(
                    FieldDescriptor(name='request_id', field_type='string', required=True, description='Request ID'),
                ),
                supported_modules=('backup',),
            ),
            StreamDefinition(
                stream_key='request_custom_tables',
                display_name='Custom Tables',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='requests',
                read_operation='get_request_with_custom_table',
                config_fields=(
                    FieldDescriptor(name='request_id', field_type='string', required=True, description='Request ID'),
                ),
            ),
            StreamDefinition(
                stream_key='posts',
                display_name='Posts',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                parent_stream='requests',
                read_operation='get_posts',
                config_fields=(
                    FieldDescriptor(name='request_id', field_type='string', required=True, description='Request ID'),
                ),
                supported_modules=('backup',),
            ),
            StreamDefinition(
                stream_key='comments',
                display_name='Comments',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                parent_stream='posts',
                read_operation='get_comments',
                config_fields=(
                    FieldDescriptor(name='post_hid', field_type='string', required=True, description='Post HID'),
                ),
                supported_modules=('backup',),
            ),
        ),
        operations=(
            OperationSpec(operation_key='get_all_groups', summary='List all groups', api_endpoint='/group/list', pagination='page'),
            OperationSpec(operation_key='get_group', summary='Get a group', api_endpoint='/group/get', required_fields=('id',)),
            OperationSpec(operation_key='get_requests', summary='List requests in a group', api_endpoint='/request/list', required_fields=('group',), pagination='page'),
            OperationSpec(operation_key='get_request', summary='Get a request', api_endpoint='/request/get', required_fields=('id',)),
            OperationSpec(operation_key='get_request_with_custom_table', summary='Get request with custom table', api_endpoint='/request/custom.table', required_fields=('id',)),
            OperationSpec(operation_key='get_posts', summary='Get posts of a request', api_endpoint='/request/post/load', required_fields=('id',)),
            OperationSpec(operation_key='get_comments', summary='Get comments of a post', api_endpoint='/request/comment/load', required_fields=('hid',)),
            OperationSpec(operation_key='create_request', summary='Create a request', api_endpoint='/request/create', required_fields=('username', 'group_id', 'name'), capability='write'),
            OperationSpec(operation_key='add_follower', summary='Add follower to a request', api_endpoint='/request/add.follower', required_fields=('id', 'username', 'followers'), capability='write'),
        ),
    )
