from __future__ import annotations

from modules.connectors.apps._definition_common import (
    BASE_CONNECTION_CONFIG,
    BASE_TOKEN_AUTH,
    GOOGLE_AUTH,
    GOOGLE_CONNECTION_CONFIG,
    AuthSpec,
    ConnectorDefinition,
    FieldDescriptor,
    OperationSpec,
    StreamDefinition,
    WriteConfig,
)


CONNECTOR_DEFINITION = ConnectorDefinition(
        connector_key='base_service',
        display_name='Base Service',
        summary='Services, tickets, and activity logs from Base Service.',
        auth_spec=BASE_TOKEN_AUTH,
        api_prefix='/extapi/v1',
        base_url_template='https://service.{domain}/extapi/v1',
        supported_modules=('backup', 'pipeline', 'automation'),
        icon='headphones',
        color='#059669',
        bg_color='#f0fdf4',
        connection_config=BASE_CONNECTION_CONFIG,
        streams=(
            StreamDefinition(
                stream_key='services',
                display_name='Services',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                read_operation='get_all_services',
                supported_modules=('backup', 'pipeline'),
            ),
            StreamDefinition(
                stream_key='compounds',
                display_name='Compounds',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                read_operation='get_all_compounds',
                supported_modules=('backup', 'pipeline'),
            ),
            StreamDefinition(
                stream_key='groups',
                display_name='Groups',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                read_operation='get_all_groups',
                supported_modules=('backup', 'pipeline'),
            ),
            StreamDefinition(
                stream_key='stages',
                display_name='Stages',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='services',
                read_operation='get_service_blocks',
                config_fields=(
                    FieldDescriptor(name='service_id', field_type='string', required=True, description='Service ID'),
                ),
            ),
            StreamDefinition(
                stream_key='tickets',
                display_name='Tickets',
                capabilities=('read', 'write'),
                sync_modes=('full_refresh', 'incremental'),
                primary_key='id',
                parent_stream='services',
                read_operation='get_all_tickets',
                write_operation='create_ticket',
                config_fields=(
                    FieldDescriptor(name='service_id', field_type='string', required=True, description='Service ID'),
                ),
                write_config=WriteConfig(
                    supported_modes=('append',),
                    default_mode='append',
                    target_kind='resource',
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
            StreamDefinition(
                stream_key='ticket_details',
                display_name='Ticket Details',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='tickets',
                read_operation='get_ticket_details',
                config_fields=(
                    FieldDescriptor(name='ticket_id', field_type='string', required=True, description='Ticket ID'),
                ),
                supported_modules=('backup',),
            ),
            StreamDefinition(
                stream_key='activity_logs',
                display_name='Activity Logs',
                capabilities=('read',),
                sync_modes=('full_refresh', 'incremental'),
                cursor_field='last_update',
                read_operation='get_ticket_activity_logs',
                supported_modules=('backup', 'pipeline'),
            ),
        ),
        operations=(
            OperationSpec(operation_key='get_all_services', summary='List all services', api_endpoint='/service/get.all', response_selector='services'),
            OperationSpec(operation_key='get_all_compounds', summary='List all compounds', api_endpoint='/compound/get.all', response_selector='compound_blocks'),
            OperationSpec(operation_key='get_all_groups', summary='List all groups', api_endpoint='/group/get.all', response_selector='groups'),
            OperationSpec(operation_key='get_service_blocks', summary='List stages for a service', api_endpoint='/service/get.stages', required_fields=('service_id',), response_selector='stages'),
            OperationSpec(operation_key='get_all_tickets', summary='List tickets for a service', api_endpoint='/ticket/get.all', required_fields=('service_id',), response_selector='tickets'),
            OperationSpec(operation_key='get_ticket_details', summary='Get ticket details', api_endpoint='/ticket/get.detail', required_fields=('id',), response_selector='ticket'),
            OperationSpec(operation_key='get_ticket_activity_logs', summary='Get ticket activity logs', api_endpoint='/ticket/get.activity.logs', pagination='page'),
            OperationSpec(operation_key='get_possible_transitions', summary='Get possible ticket transitions', api_endpoint='/ticket/get.possible.actions', required_fields=('ticket_id', 'username')),
            OperationSpec(operation_key='create_ticket', summary='Create a ticket', api_endpoint='/ticket/create', required_fields=('username', 'service_id', 'block_id', 'name'), capability='write'),
            OperationSpec(operation_key='update_ticket', summary='Update a ticket', api_endpoint='/ticket/edit', required_fields=('service_id', 'ticket_id', 'username', 'name'), capability='write'),
            OperationSpec(operation_key='update_ticket_custom_fields', summary='Update ticket custom fields', api_endpoint='/ticket/edit.custom.fields', required_fields=('service_id', 'ticket_id', 'username', 'custom_field_ids'), capability='write'),
            OperationSpec(operation_key='assign_ticket', summary='Assign a ticket', api_endpoint='/ticket/assign', required_fields=('ticket_id', 'username', 'assignees'), capability='write'),
            OperationSpec(operation_key='execute_ticket', summary='Execute a ticket step', api_endpoint='/ticket/execute', required_fields=('ticket_id', 'username'), capability='write'),
            OperationSpec(operation_key='move_ticket_to_block', summary='Move ticket to a block', api_endpoint='/ticket/move.to.block', required_fields=('ticket_id', 'username', 'next_block_id'), capability='write'),
            OperationSpec(operation_key='move_ticket_back', summary='Move ticket back', api_endpoint='/ticket/move.back', required_fields=('ticket_id', 'username'), capability='write'),
        ),
    )
