"""initial product schema

Revision ID: df842f034dc0
Revises: 
Created: 2026-09-04 17:56:04.971060
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'df842f034dc0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'API', 'WEBHOOK', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_label', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', name='audit_result'), nullable=False),
    sa.Column('before_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=48), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_index('ix_audit_ws_created', 'audit_events', ['workspace_id', 'created_at'], unique=False)
    op.create_table('engine_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_type', sa.Enum('N8N_CORE', name='engine_type'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('endpoint_ref', sa.String(length=160), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.Column('adapter_contract_version', sa.String(length=16), nullable=False),
    sa.Column('compiler_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'OFFLINE', name='engine_instance_status'), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_probe_message', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('capacity_class', sa.String(length=32), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engine_instances'))
    )
    op.create_table('node_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('TRIGGER', 'ACTION', 'LOGIC', 'DATA', 'APP', name='node_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('product_schema_version', sa.Integer(), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capability_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('certification', sa.Enum('SUPPORTED', 'BETA', 'HIDDEN', 'BLOCKED', name='certification'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DEPRECATED', name='node_status'), nullable=False),
    sa.Column('engine_binding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('security_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('docs_ref', sa.String(length=255), nullable=True),
    sa.Column('last_certified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spec_hash', sa.String(length=64), nullable=False),
    sa.Column('known_issues', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_definitions'))
    )
    op.create_index(op.f('ix_node_definitions_node_key'), 'node_definitions', ['node_key'], unique=True)
    op.create_index('ix_nodes_status_certification_category', 'node_definitions', ['status', 'certification', 'category'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('EXECUTION_FAILED', 'CONSECUTIVE_FAILURES', 'CREDENTIAL_INVALID', 'SCHEDULE_MISSED', 'WEBHOOK_AUTH_FAILURE_BURST', 'ENGINE_DEGRADED', 'VERSION_INCOMPATIBLE', name='alert_event_type'), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ACKNOWLEDGED', name='notification_status'), nullable=False),
    sa.Column('remediation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_dedup_key'), 'notifications', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_index('ix_notifications_ws_status_created', 'notifications', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('wrapped_data_key', sa.Text(), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('field_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets'))
    )
    op.create_index(op.f('ix_secrets_ref'), 'secrets', ['ref'], unique=True)
    op.create_index(op.f('ix_secrets_workspace_id'), 'secrets', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_change_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('session_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='workspace_status'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('engine_instance_id', sa.UUID(), nullable=True),
    sa.Column('max_concurrent_executions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_instance_id'], ['engine_instances.id'], name=op.f('fk_workspaces_engine_instance_id_engine_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('credential_type', sa.Enum('NONE', 'HTTP_BASIC', 'BEARER', 'HEADER_API_KEY', 'QUERY_API_KEY', name='credential_type'), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('public_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVALID', 'REVOKED', 'DELETED', name='credential_status'), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_credentials_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_credentials_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_credential_ws_name')
    )
    op.create_index(op.f('ix_credentials_workspace_id'), 'credentials', ['workspace_id'], unique=False)
    op.create_index('ix_credentials_ws_status', 'credentials', ['workspace_id', 'status'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'AUTOMATION_ADMIN', 'AUTOMATION_BUILDER', 'OPERATOR', 'ANALYST', 'AUDITOR', 'PLATFORM_ADMIN', name='member_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_membership_ws_user')
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='workflow_status'), nullable=False),
    sa.Column('published_version_id', sa.UUID(), nullable=True),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type_cache', sa.Enum('MANUAL', 'WEBHOOK', 'SCHEDULE', name='trigger_type'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['workflow_versions.id'], name=op.f('fk_workflows_active_version_id_workflow_versions'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workflows_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_version_id'], ['workflow_versions.id'], name=op.f('fk_workflows_published_version_id_workflow_versions'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_workflows_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workflows_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_index(op.f('ix_workflows_workspace_id'), 'workflows', ['workspace_id'], unique=False)
    op.create_index('ix_workflows_ws_active_version', 'workflows', ['workspace_id', 'active_version_id'], unique=False)
    op.create_index('ix_workflows_ws_status_updated', 'workflows', ['workspace_id', 'status', 'updated_at'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('EXECUTION_FAILED', 'CONSECUTIVE_FAILURES', 'CREDENTIAL_INVALID', 'SCHEDULE_MISSED', 'WEBHOOK_AUTH_FAILURE_BURST', 'ENGINE_DEGRADED', 'VERSION_INCOMPATIBLE', name='alert_event_type'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_alert_rules_workflow_id_workflows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_alert_rules_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_workspace_id'), 'alert_rules', ['workspace_id'], unique=False)
    op.create_index('ix_alert_rules_ws_event', 'alert_rules', ['workspace_id', 'event_type'], unique=False)
    op.create_table('workflow_drafts',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_hash', sa.String(length=64), nullable=False),
    sa.Column('product_schema_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('validation_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['saved_by'], ['users.id'], name=op.f('fk_workflow_drafts_saved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_drafts_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', name=op.f('pk_workflow_drafts'))
    )
    op.create_index(op.f('ix_workflow_drafts_workspace_id'), 'workflow_drafts', ['workspace_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_hash', sa.String(length=64), nullable=False),
    sa.Column('product_schema_version', sa.Integer(), nullable=False),
    sa.Column('compiler_version', sa.String(length=32), nullable=False),
    sa.Column('engine_compatibility_set', sa.String(length=64), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_workflow_versions_published_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_versions_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_versions')),
    sa.UniqueConstraint('workflow_id', 'version_number', name='uq_version_workflow_number')
    )
    op.create_index('ix_versions_workflow_number', 'workflow_versions', ['workflow_id', 'version_number'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workspace_id'), 'workflow_versions', ['workspace_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_id', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('version_kind', sa.Enum('DRAFT', 'PUBLISHED', name='version_kind'), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.Column('graph_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_hash', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'WEBHOOK', 'SCHEDULE', name='trigger_type'), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('retry_of_execution_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'DISPATCHING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCEL_REQUESTED', 'CANCELLED', 'TIMED_OUT', 'FAILED_TO_START', 'ENGINE_INTERRUPTED', name='execution_status'), nullable=False),
    sa.Column('error_category', sa.String(length=48), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('failed_node_name', sa.String(length=200), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technical_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_ref', sa.String(length=128), nullable=True),
    sa.Column('engine_instance_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['engine_instance_id'], ['engine_instances.id'], name=op.f('fk_executions_engine_instance_id_engine_instances')),
    sa.ForeignKeyConstraint(['retry_of_execution_id'], ['executions.id'], name=op.f('fk_executions_retry_of_execution_id_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_executions_triggered_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_executions_workflow_id_workflows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_executions_workflow_version_id_workflow_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_executions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index('ix_executions_dispatch', 'executions', ['status', 'queued_at'], unique=False)
    op.create_index('ix_executions_idempotency', 'executions', ['workspace_id', 'idempotency_key'], unique=False)
    op.create_index(op.f('ix_executions_short_id'), 'executions', ['short_id'], unique=False)
    op.create_index(op.f('ix_executions_workflow_id'), 'executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_executions_workspace_id'), 'executions', ['workspace_id'], unique=False)
    op.create_index('ix_executions_ws_status_queued', 'executions', ['workspace_id', 'status', 'queued_at'], unique=False)
    op.create_index('ix_executions_ws_workflow_started', 'executions', ['workspace_id', 'workflow_id', 'started_at'], unique=False)
    op.create_table('trigger_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'WEBHOOK', 'SCHEDULE', name='trigger_type'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=True),
    sa.Column('webhook_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overlap_policy', sa.Enum('SKIP_IF_RUNNING', 'ALLOW', name='overlap_policy'), nullable=False),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], name=op.f('fk_trigger_bindings_activated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_trigger_bindings_workflow_id_workflows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_trigger_bindings_workflow_version_id_workflow_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trigger_bindings')),
    sa.UniqueConstraint('public_key', name='uq_trigger_public_key')
    )
    op.create_index(op.f('ix_trigger_bindings_workflow_id'), 'trigger_bindings', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_trigger_bindings_workspace_id'), 'trigger_bindings', ['workspace_id'], unique=False)
    op.create_index('ix_triggers_due', 'trigger_bindings', ['enabled', 'next_run_at'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_logs_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_logs'))
    )
    op.create_index('ix_execution_logs_exec_seq', 'execution_logs', ['execution_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_execution_logs_execution_id'), 'execution_logs', ['execution_id'], unique=False)
    op.create_table('execution_node_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='node_run_status'), nullable=False),
    sa.Column('execution_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('input_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('branch_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_node_results_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_node_results'))
    )
    op.create_index(op.f('ix_execution_node_results_execution_id'), 'execution_node_results', ['execution_id'], unique=False)
    op.create_index('ix_node_results_execution', 'execution_node_results', ['execution_id', 'node_id', 'execution_index'], unique=False)
    # The circular pair, added once both tables exist.
    #
    # `use_alter=True` in the model is what lets the two CREATE TABLEs be
    # ordered at all -- but Alembic's autogenerate does not render an ALTER-only
    # constraint, so without these two lines the database ends up without them
    # and `alembic check` reports a permanent diff.
    op.create_foreign_key(
        op.f('fk_workflows_published_version_id_workflow_versions'),
        'workflows', 'workflow_versions', ['published_version_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        op.f('fk_workflows_active_version_id_workflow_versions'),
        'workflows', 'workflow_versions', ['active_version_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First: the circular constraints. Dropping a table that is still
    # referenced fails, and these two are the only references Alembic did
    # not order for itself.
    op.drop_constraint(
        op.f('fk_workflows_active_version_id_workflow_versions'),
        'workflows', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_workflows_published_version_id_workflow_versions'),
        'workflows', type_='foreignkey',
    )
    op.drop_index('ix_node_results_execution', table_name='execution_node_results')
    op.drop_index(op.f('ix_execution_node_results_execution_id'), table_name='execution_node_results')
    op.drop_table('execution_node_results')
    op.drop_index(op.f('ix_execution_logs_execution_id'), table_name='execution_logs')
    op.drop_index('ix_execution_logs_exec_seq', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index('ix_triggers_due', table_name='trigger_bindings')
    op.drop_index(op.f('ix_trigger_bindings_workspace_id'), table_name='trigger_bindings')
    op.drop_index(op.f('ix_trigger_bindings_workflow_id'), table_name='trigger_bindings')
    op.drop_table('trigger_bindings')
    op.drop_index('ix_executions_ws_workflow_started', table_name='executions')
    op.drop_index('ix_executions_ws_status_queued', table_name='executions')
    op.drop_index(op.f('ix_executions_workspace_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_workflow_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_short_id'), table_name='executions')
    op.drop_index('ix_executions_idempotency', table_name='executions')
    op.drop_index('ix_executions_dispatch', table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_workflow_versions_workspace_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_index('ix_versions_workflow_number', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_drafts_workspace_id'), table_name='workflow_drafts')
    op.drop_table('workflow_drafts')
    op.drop_index('ix_alert_rules_ws_event', table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_workspace_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('ix_workflows_ws_status_updated', table_name='workflows')
    op.drop_index('ix_workflows_ws_active_version', table_name='workflows')
    op.drop_index(op.f('ix_workflows_workspace_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_credentials_ws_status', table_name='credentials')
    op.drop_index(op.f('ix_credentials_workspace_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_secrets_workspace_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_ref'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index('ix_notifications_ws_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedup_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_nodes_status_certification_category', table_name='node_definitions')
    op.drop_index(op.f('ix_node_definitions_node_key'), table_name='node_definitions')
    op.drop_table('node_definitions')
    op.drop_table('engine_instances')
    op.drop_index('ix_audit_ws_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')

    # Postgres keeps an enum type after the last table using it is dropped, so
    # a downgrade followed by an upgrade fails with "type already exists". These
    # are the types the CREATE TABLEs above created implicitly.
    for enum_name in (
        'actor_type',
        'alert_event_type',
        'audit_result',
        'certification',
        'credential_status',
        'credential_type',
        'engine_instance_status',
        'engine_type',
        'execution_status',
        'member_role',
        'node_category',
        'node_run_status',
        'node_status',
        'notification_status',
        'overlap_policy',
        'trigger_type',
        'version_kind',
        'workflow_status',
        'workspace_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
