from __future__ import annotations

from modules.connectors.apps._definition_common import (
    BASE_CONNECTION_CONFIG,
    BASE_TOKEN_AUTH,
    GOOGLE_AUTH,
    GOOGLE_CONNECTION_CONFIG,
    AuthSpec,
    ConnectorDefinition,
    FieldDescriptor,
    OperationSpec,
    StreamDefinition,
    WriteConfig,
)


CONNECTOR_DEFINITION = ConnectorDefinition(
        connector_key='base_wework',
        display_name='Base WeWork',
        summary='Departments, projects, tasks and subtasks from Base WeWork.',
        auth_spec=BASE_TOKEN_AUTH,
        api_prefix='/extapi/v3',
        base_url_template='https://wework.{domain}/extapi/v3',
        supported_modules=('backup', 'pipeline', 'automation'),
        icon='building-2',
        color='#2563eb',
        bg_color='#eff6ff',
        connection_config=BASE_CONNECTION_CONFIG,
        streams=(
            StreamDefinition(
                stream_key='departments',
                display_name='Departments',
                capabilities=('read', 'write'),
                sync_modes=('full_refresh',),
                primary_key='id',
                read_operation='get_all_departments',
                write_operation='create_department',
                write_config=WriteConfig(
                    supported_modes=('append',),
                    default_mode='append',
                    target_kind='resource',
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
            StreamDefinition(
                stream_key='projects',
                display_name='Projects',
                capabilities=('read', 'write'),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='departments',
                read_operation='get_all_projects',
                write_operation='create_project',
                config_fields=(
                    FieldDescriptor(name='department_id', field_type='string', required=False, description='Department ID'),
                ),
                write_config=WriteConfig(
                    supported_modes=('append',),
                    default_mode='append',
                    target_kind='resource',
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
            StreamDefinition(
                stream_key='tasks',
                display_name='Tasks',
                capabilities=('read', 'write'),
                sync_modes=('full_refresh', 'incremental'),
                primary_key='id',
                parent_stream='projects',
                read_operation='get_project_tasks',
                write_operation='create_task',
                config_fields=(
                    FieldDescriptor(name='project_id', field_type='string', required=True, description='Project ID'),
                ),
                write_config=WriteConfig(
                    supported_modes=('append',),
                    default_mode='append',
                    target_kind='resource',
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
            StreamDefinition(
                stream_key='subtasks',
                display_name='Subtasks',
                capabilities=('read', 'write'),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='tasks',
                read_operation='get_task',
                write_operation='create_subtask',
                config_fields=(
                    FieldDescriptor(name='project_id', field_type='string', required=True, description='Project ID'),
                ),
                write_config=WriteConfig(
                    supported_modes=('append',),
                    default_mode='append',
                    target_kind='resource',
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
            StreamDefinition(
                stream_key='tasklists',
                display_name='Tasklists',
                capabilities=('read',),
                sync_modes=('full_refresh',),
                primary_key='id',
                parent_stream='projects',
                read_operation='get_tasklist',
                config_fields=(
                    FieldDescriptor(name='project_id', field_type='string', required=True, description='Project ID'),
                ),
                supported_modules=('backup', 'pipeline', 'automation'),
            ),
        ),
        operations=(
            OperationSpec(operation_key='get_all_departments', summary='List all departments', api_endpoint='/dept/list'),
            OperationSpec(operation_key='get_department', summary='Get a department', api_endpoint='/dept/get', required_fields=('id',)),
            OperationSpec(operation_key='get_all_projects', summary='List all projects', api_endpoint='/project/list'),
            OperationSpec(operation_key='get_project_full', summary='Get full project details', api_endpoint='/project/get.full', required_fields=('id',)),
            OperationSpec(operation_key='get_task', summary='Get a task', api_endpoint='/task/get', required_fields=('id',)),
            OperationSpec(operation_key='get_project_tasks', summary='List tasks by project', api_endpoint='/task/project', required_fields=('id', 'username'), pagination='page'),
            OperationSpec(operation_key='get_tasklist', summary='Get a tasklist', api_endpoint='/tasklist/get', required_fields=('id',)),
            OperationSpec(operation_key='create_department', summary='Create a department', api_endpoint='/dept/create', required_fields=('username', 'name'), capability='write'),
            OperationSpec(operation_key='edit_department', summary='Edit a department', api_endpoint='/dept/edit', required_fields=('username', 'id', 'name'), capability='write'),
            OperationSpec(operation_key='remove_department', summary='Remove a department', api_endpoint='/dept/remove', required_fields=('username', 'id'), capability='write'),
            OperationSpec(operation_key='create_project', summary='Create a project', api_endpoint='/project/create', required_fields=('username', 'metatype', 'name', 'external'), capability='write'),
            OperationSpec(operation_key='edit_project', summary='Edit a project', api_endpoint='/project/edit', required_fields=('username', 'id', 'name'), capability='write'),
            OperationSpec(operation_key='create_task', summary='Create a task', api_endpoint='/task/create', required_fields=('username', 'id', 'name'), capability='write'),
            OperationSpec(operation_key='create_subtask', summary='Create a subtask', api_endpoint='/subtask/create', required_fields=('username', 'parent_id', 'name'), capability='write'),
            OperationSpec(operation_key='edit_task', summary='Edit a task', api_endpoint='/task/edit', required_fields=('username', 'id'), capability='write'),
            OperationSpec(operation_key='edit_task_extra', summary='Edit task extra fields', api_endpoint='/task/edit.extra', required_fields=('username', 'id'), capability='write'),
            OperationSpec(operation_key='mark_task_done', summary='Mark task as done', api_endpoint='/task/status/mark.done', required_fields=('username', 'id'), capability='write'),
            OperationSpec(operation_key='delete_task', summary='Delete a task', api_endpoint='/task/remove', required_fields=('username', 'id'), capability='write'),
            OperationSpec(operation_key='add_task_followers', summary='Add task followers', api_endpoint='/task/add.followers', required_fields=('username', 'id', 'followers'), capability='write'),
        ),
    )
